### ISSUE TITLE
XML tags losing 'gco; gmd, etc...' prefixes when serializing

### ISSUE THREAD

**Issue by grwhumphries** [consbio/gis-metadata-parser#2]
Just using the serialize function here to output the data, and writing the new xml file out, I notice that the structure of the original XML isn't preserved.   The tags <gmd:... >  and <gco:...? etc.. that are standard for ISO 19139 metadata are lost. 

Basic structure looks like this from input: 

<?xml version="1.0" encoding="UTF-8"?>

-<gmd:MD_Metadata xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:gts="http://www.isotc211.org/2005/gts" xmlns:gss="http://www.isotc211.org/2005/gss" xmlns:gsr="http://www.isotc211.org/2005/gsr" xmlns:gmx="http://www.isotc211.org/2005/gmx" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:srv="http://www.isotc211.org/2005/srv" xmlns:gmd="http://www.isotc211.org/2005/gmd">
+<gmd:fileIdentifier>
+<gmd:language>
+<gmd:hierarchyLevel>
+<gmd:contact>
+<gmd:dateStamp>
+<gmd:metadataStandardName>
+<gmd:metadataStandardVersion>
+<gmd:referenceSystemInfo>
+<gmd:identificationInfo>
+<gmd:distributionInfo>
+<gmd:dataQualityInfo>
</gmd:MD_Metadata>

Comes out like this: 

<?xml version="1.0" encoding="UTF-8"?>
-<MD_Metadata>
fileIdentifier
language
hierarchyLevel
contact
etc...

I believe those prefixes are quite important for ISO quality standardss

**Comment by dharvey-consbio** [comment]
The ISO standard is very verbose. I had to make a choice about how much of it I was going to support. I decided to strip namespaces because there are nuances that are difficult to manage, and even more difficult to convert between standards.

So, at least for now, the scope of this project is to provide a developer with a simple, easy-to-use tool that reads-in, updates, converts and writes out metadata content between standards. For now it has to focus on what the standards have in common to do what it does well.

But thanks for the feedback. I will be pondering this to see if I can figure out an elegant way to improve support for ISO standard namespaces.
